/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteJjhhjjhArgs } from "./DeleteJjhhjjhArgs";
import { JjhhjjhFindManyArgs } from "./JjhhjjhFindManyArgs";
import { JjhhjjhFindUniqueArgs } from "./JjhhjjhFindUniqueArgs";
import { Jjhhjjh } from "./Jjhhjjh";
import { JjhhjjhService } from "../jjhhjjh.service";

@graphql.Resolver(() => Jjhhjjh)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class JjhhjjhResolverBase {
  constructor(
    protected readonly service: JjhhjjhService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Jjhhjjh",
    action: "read",
    possession: "any",
  })
  async _jjhhjjhsMeta(
    @graphql.Args() args: JjhhjjhFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Jjhhjjh])
  @nestAccessControl.UseRoles({
    resource: "Jjhhjjh",
    action: "read",
    possession: "any",
  })
  async jjhhjjhs(
    @graphql.Args() args: JjhhjjhFindManyArgs
  ): Promise<Jjhhjjh[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Jjhhjjh, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Jjhhjjh",
    action: "read",
    possession: "own",
  })
  async jjhhjjh(
    @graphql.Args() args: JjhhjjhFindUniqueArgs
  ): Promise<Jjhhjjh | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Jjhhjjh)
  @nestAccessControl.UseRoles({
    resource: "Jjhhjjh",
    action: "delete",
    possession: "any",
  })
  async deleteJjhhjjh(
    @graphql.Args() args: DeleteJjhhjjhArgs
  ): Promise<Jjhhjjh | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
